version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: test_db
    restart: always
    environment:
      POSTGRES_USER: anil
      POSTGRES_PASSWORD: anil123
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
